/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_zeromq_zyre_ZyreEvent */

#ifndef _Included_org_zeromq_zyre_ZyreEvent
#define _Included_org_zeromq_zyre_ZyreEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1init
  (JNIEnv *, jclass);

/*
 * Class:     org_zeromq_zyre_ZyreEvent
 * Method:    __destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_zeromq_zyre_ZyreEvent__1_1destroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
